BEGIN TRANSACTION;

DROP TABLE IF EXISTS R;
DROP TABLE IF EXISTS F;



CREATE TABLE R(A INT, B INT, C INT, D INT, E INT, F INT);
CREATE TABLE F(x VARCHAR(10), y VARCHAR(10), violation BOOLEAN, motivation VARCHAR(200));  

COMMIT;

BEGIN TRANSACTION;

DROP TABLE IF EXISTS R1;
DROP TABLE IF EXISTS R2;
DROP TABLE IF EXISTS F1;
DROP TABLE IF EXISTS F2;

CREATE TABLE R1(A INT, B INT, C INT, E INT, F INT);
CREATE TABLE R2(E INT, D INT);
CREATE TABLE F1(x VARCHAR(10), y VARCHAR(10), violation BOOLEAN, motivation VARCHAR(200));  
CREATE TABLE F2(x VARCHAR(10), y VARCHAR(10), violation BOOLEAN, motivation VARCHAR(200));  

COMMIT;

--BEGIN TRANSACTION;
--
--DROP TABLE IF EXISTS R3;
--DROP TABLE IF EXISTS R4;
--DROP TABLE IF EXISTS F3;
--DROP TABLE IF EXISTS F4;
--
--CREATE TABLE R3(B INT, C INT, E INT, F INT);
--CREATE TABLE R4(E INT, A INT);
--
--CREATE TABLE F3(x VARCHAR(10), y VARCHAR(10), violation BOOLEAN, motivation VARCHAR(200));  
--CREATE TABLE F4(x VARCHAR(10), y VARCHAR(10), violation BOOLEAN, motivation VARCHAR(200));
--
--COMMIT;